### ISSUE TITLE
Operator-SDK support only gs.k8s.io/kubebuilder/v3/pkg/plugin not sigs.k8s.io/kubebuilder/v4/pkg/config".Version

### ISSUE THREAD

**Issue by xstefank** [operator-framework/java-operator-plugins#157]
#### What did you do?

I'm trying to update operator-sdk to java-operator-plugins v0.11.0.

#### What did you expect to see?

Clean integration.

#### What did you see instead? Under which circumstances?

```
internal/cmd/operator-sdk/cli/cli.go:174:4: cannot use &quarkusv1.Plugin{} (value of type *"github.com/operator-framework/java-operator-plugins/pkg/quarkus/v1beta".Plugin) as "sigs.k8s.io/kubebuilder/v3/pkg/plugin".Plugin value in argument to cli.WithPlugins: *"github.com/operator-framework/java-operator-plugins/pkg/quarkus/v1beta".Plugin does not implement "sigs.k8s.io/kubebuilder/v3/pkg/plugin".Plugin (wrong type for method SupportedProjectVersions)
		have SupportedProjectVersions() []"sigs.k8s.io/kubebuilder/v4/pkg/config".Version
		want SupportedProjectVersions() []"sigs.k8s.io/kubebuilder/v3/pkg/config".Version
```

#### Possible Solution

This was introduced in https://github.com/operator-framework/java-operator-plugins/commit/059d5fc69ecded316ede9b7cae66ef9937161338. Possibly degrade kubebuilder to v3 as it seems that operator-sdk is not updating it.

**Comment by xstefank** [comment]
@metacosm what do you think? Can I revert that upgrade commit or what is the best way to proceed here?

**Comment by metacosm** [comment]
Yes, we're bound to use whichever kubebuilder version is used by the plugin host…
